import { Button } from "@mui/material"
import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Link href={"/"}><Button>Back to site</Button></Link>
        {children}
        </body>
    </html>
  )
}
